### ISSUE TITLE
[Crash Report] Server crashed when placing mob card in mob farm.  Can't connect back.

### ISSUE THREAD

**Issue by KudanaVadmont** [MarkusBordihn/BOs-Easy-Mob-Farm#93]
**Minecraft and Mod version** 🐞
The used Minecraft and Mod version.
Curse Forge Launcher, Fabric-loader 0.16.9-1.21.3

**Description of the crash** 💥
When placing a mob card inside of a mob farm, the server crashed and cannot be started back up.  The error occurred while changing the block tile to an owner.

**Steps to reproduce the crash** ⚙️

1.Place Mob Farm
2.Place Mob Card In Farm
3.Crash

**Expected behavior before the crash** ✔️
Place mob card in farm, and go from there, we haven't got this far.  It didn't work before the update.

**Logs** 📝
To speed up the diagnosis, please provide the following files if possible:

[crash-2024-12-04_07.04.00-client.txt](https://github.com/user-attachments/files/18010299/crash-2024-12-04_07.04.00-client.txt)

These logs contain essential details that will help me identify the problem and offer more accurate
assistance.
You can upload the logs to https://gist.github.com/ or https://mclo.gs/ and share the link here.

**Additional context** 📋
Thank you for this mod, It looks amazing, can't wait till I can use use it.

**Comment by MarkusBordihn** [comment]
Thank you for the report! I was able to reproduce the issue, and it appears to be related to the Physics Mod. 
Disabling the mod should allow the world to load correctly.

![image](https://github.com/user-attachments/assets/4a15f0c6-7e72-4c58-953e-66bc66d7ca07)

Based on the crash log, it seems that the Physics Mod attempts to hide specific parts of the dummy mob inside the farm. However, this fails because the dummy mob is intentionally limited in functionality.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5864()" because "entity" is null
	at knot//net.diebuddies.config.ConfigCloth.getCustomizationParts(ConfigCloth.java:121)
	at knot//net.diebuddies.physics.settings.cloth.ClothConstants.hideProperParts(ClothConstants.java:87)
	at knot//net.minecraft.class_922.handler$bam000$physicsmod$hideModelParts(class_922.java:1573)
	at knot//net.minecraft.class_922.method_4054(class_922.java:95)
	at knot//net.minecraft.class_9990.method_4054(class_9990.java:24)
	at knot//net.minecraft.class_9990.method_3936(class_9990.java:10)
	at knot//de.markusbordihn.easymobfarm.client.renderer.blockentity.MobFarmBlockEntityRenderer.render(MobFarmBlockEntityRenderer.java:129)
	at knot//de.markusbordihn.easymobfarm.client.renderer.blockentity.MobFarmBlockEntityRenderer.method_3569(MobFarmBlockEntityRenderer.java:42)
	at knot//net.minecraft.class_824.method_23079(class_824.java:90)
	at knot//net.minecraft.class_824.method_23081(class_824.java:79)
	at knot//net.minecraft.class_824.method_3554(class_824.java:104)
	at knot//net.minecraft.class_824.method_3555(class_824.java:79)
	at knot//net.minecraft.class_761.method_62208(class_761.java:909)
	at knot//net.minecraft.class_761.method_62214(class_761.java:651)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:556)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)
	at knot//net.minecraft.class_757.method_3192(class_757.java:491)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
	
Unfortunately, I cannot check the source code of the Physics Mod, but implementing a simple null check on their side should resolve this issue, not only for this mod but also for others that use dummy mobs.

I recommend reporting this issue to the Physics Mod author for a fix.

**Comment by KudanaVadmont** [comment]
Ahhh ok!  Thank you!
